name: release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0

jobs:
  release:
    runs-on: ubuntu-latest
    name: release
    steps:
      - uses: actions/checkout@v2
      - name: Login docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.IMAGE_PUSH_USERNAME }}
          password: ${{ secrets.IMAGE_PUSH_TOKEN }}
      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.CI_ACCESS_TOKEN }}
          USERNAME: ${{ secrets.CI_USERNAME }}
        run: git config --global url."https://${USERNAME}:${TOKEN}@github.com".insteadOf "https://github.com"
      - name: release
        run: make release
        env:
          IMAGE_PROJECT:  ${{ secrets.RELEASE_IMAGE_PROJECT }}
          IMAGE_REPO:  ${{ secrets.IMAGE_REPO }}

      - name: Generate draft release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          tag_name: ${{ env.TAG }}
          name: Release ${{ env.TAG }}
          files: out/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}